name: Автопостинг новин

# Коли запускати
on:
  schedule:
    - cron: '0 7 * * *'
    - cron: '30 8 * * *'  # 10:30
    - cron: '0 10 * * *'   # 12:00
    - cron: '30 11 * * *'  # 13:30
    - cron: '0 13 * * *'   # 15:00
    - cron: '30 14 * * *'  # 16:30
    - cron: '0 16 * * *'   # запуск о 09:07 CEST (7:07 UTC) — приклад
  workflow_dispatch:        # дозволяє запуск вручну

jobs:
  post-news:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      GEMINI_API: ${{ secrets.GEMINI_API }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    steps:
      # 1. Клонування репозиторію
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Встановлення Python
      - name: Встановлення Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Встановлення залежностей
      - name: Встановлення залежностей
        run: |
          pip install -r requirements.txt
      # Добавлення дати
      - name: Получение текущей даты
        id: date
        run: echo "today=$(date +'%d.%m.%Y')" >> $GITHUB_OUTPUT

      # 4. Запуск скрипта
      - name: Запуск скрипта
        run: |
          python main.py
      # 5.  Налаштування git
      - name: Налаштування git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "@vasilenkoilla898@gmail.com"
      # 6.Комміт результатів парсингу
      - name: Комміт результатів парсингу
        run: |
          git add .
          git commit -m "Добавлены результаты парсинга за ${{ steps.date.outputs.today }}" || echo "Нет изменений"
          git push

