name: Автопостинг новин

# Коли запускати
on:
  schedule:
    - cron: '0 7 * * *'
    - cron: '30 8 * * *'  # 10:30
    - cron: '0 10 * * *'   # 12:00
    - cron: '30 11 * * *'  # 13:30
    - cron: '0 13 * * *'   # 15:00
    - cron: '30 14 * * *'  # 16:30
    - cron: '0 16 * * *'   # запуск о 09:07 CEST (7:07 UTC) — приклад
  workflow_dispatch:        # дозволяє запуск вручну

jobs:
  post-news:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      GEMINI_API: ${{ secrets.GEMINI_API }}

    steps:
      # 1. Клонування репозиторію
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Встановлення Python
      - name: Встановлення Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Встановлення залежностей
      - name: Встановлення залежностей
        run: |
          pip install -r requirements.txt

      # 4. Запуск скрипта
      - name: Запуск скрипта
        run: |
          python main.py
